<?php
/**
 * ConfigmanagerGetConfigRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Configmanager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * configmanager/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Configmanager\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ConfigmanagerGetConfigRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ConfigmanagerGetConfigRequest
 * @package     GeminiCommerce\Configmanager
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConfigmanagerGetConfigRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ConfigmanagerGetConfigRequest"
     */
    public function testConfigmanagerGetConfigRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "business_domain"
     */
    public function testPropertyBusinessDomain()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
