<?php
/**
 * ConfigManagerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Configmanager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Config Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Configmanager\Test\Api;

use \GeminiCommerce\Configmanager\Configuration;
use \GeminiCommerce\Configmanager\ApiException;
use \GeminiCommerce\Configmanager\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConfigManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Configmanager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfigManagerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for configManagerBulkSetConfigs
     *
     * BulkSetConfigs.
     *
     */
    public function testConfigManagerBulkSetConfigs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configManagerGetConfig
     *
     * GetConfig.
     *
     */
    public function testConfigManagerGetConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configManagerGetTenantIdByCode
     *
     * .
     *
     */
    public function testConfigManagerGetTenantIdByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
